pipeline:
  # Prepare toolkit locally so we can clone and install sites :
  install-tookit:
    image: fpfis/php56-dev
    commands:
      - composer require ec-europa/toolkit:3.*
      - PROJECT=$(pwd) composer run-script toolkit-install -d ./vendor/ec-europa/toolkit
    volumes:
      - /cache:/cache

  # Run PHPCS on module directory
  phpcs:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing test-run-phpcs -Dphpcs.files=nesrm_cookbook
